version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
     POSTGRES_PASSWORD: postgrespw
     POSTGRES_USER: postgres
     POSTGRES_DB: banking_db
    ports:
      - "5432:5432"
